### ISSUE TITLE
Meetup mentor for Rust meetups

### ISSUE THREAD

**Issue by jmswisher** [mozilla/community-spaces#12]
Identify, confirm, and schedule Q&A session with a mentor for Rust meetups.

**Comment by jmswisher** [comment]
Felix Klock (Rust engineer and co-organizer of Rust Paris) is confirmed; waiting on response from him to schedule.

**Comment by bobreyes** [comment]
We are creating a local Rust Mentors group here in MNL. The team is composed of volunteers, all with programming/developer backgrounds (as their daytime jobs). During our first meeting, one of the points raised is the lack of proper documentation and support from the Rust core group. We reached out to Aaron Turon via email, but we were pointed to the global Rust Community IRC and Forum instead.
