### ISSUE TITLE
Meetup mentor for Firefox DevTools meetups

### ISSUE THREAD

**Issue by jmswisher** [mozilla/community-spaces#16]
Identify, confirm, and schedule a Q&A session with a mentor for Firefox DevTools meetups.

**Comment by jmswisher** [comment]
I haven't been able to identify anybody who has actually led Dev Tools meetups. Might merge this one with "Web Development".

**Comment by MichaelKohler** [comment]
In Switzerland we did a Firefox Hackathon (full day) mostly around Dev Tools. Maybe these posts would help out:

https://michaelkohler.info/2016/firefox-hackathon-zurich-april-2016
https://michaelkohler.info/2016/alpha-review-using-janitor-to-contribute-to-firefox
