### ISSUE TITLE
Jakarta - May 2016 Report

### ISSUE THREAD

**Issue by brianking** [mozilla/community-spaces#19]
Compile and publish the space report for Jakarta, for May 2016.

**Comment by yofiesetiawan** [comment]
Compiled and published the space report for Jakarta, for May 2016.

https://docs.google.com/document/d/1_gBm_RHwI2DKXRNqY6QAI3Q-N7Je_Y_kceWI9kRl3OA/edit?usp=sharing

**Comment by brianking** [comment]
Thank you Yofie.
