### ISSUE TITLE
Request Discourse Category

### ISSUE THREAD

**Issue by brianking** [mozilla/community-spaces#2]
As I wrote on Telegram yesterday:

I think it is a good idea to setup a Discourse category for Community Spaces
Under the Participation category perhaps?
https://discourse.mozilla-community.org/c/participation
Or as a separate high-level category perhaps, so we can have per-city sub-categories?

**Comment by brianking** [comment]
On hold for now.

**Comment by brianking** [comment]
Do we still want this? @irvin @yofiesetiawan

**Comment by irvin** [comment]
I think we can pending for now
