### ISSUE TITLE
Manila - May 2016 Report

### ISSUE THREAD

**Issue by brianking** [mozilla/community-spaces#20]
Compile and publish the space report for Manila, for May 2016.

**Comment by bobreyes** [comment]
This is done already. Thanks!

https://docs.google.com/document/d/1PoeXVo4Ta7rfBWGs2nmEgmz2AZe2_di5q8NasOvGMyc/edit?usp=sharing

**Comment by brianking** [comment]
Thanks @bobreyes I added in a few comments for things that need clarification / completion.
