### ISSUE TITLE
Taipei - May 2016 Report

### ISSUE THREAD

**Issue by brianking** [mozilla/community-spaces#21]
Compile and publish the space report for Taipei, for May 2016.

**Comment by brianking** [comment]
Any update on this @bobchao ?

**Comment by bobchao** [comment]
Hi, it's actually in the shared folder for a long time, sorry didn't update here
https://docs.google.com/document/d/10rMyN9Dpl_kF8l_lTP4KKskqPcD6U4GR00zgwH1Imw4/edit

**Comment by brianking** [comment]
Excellent report, thanks Bob.
