### ISSUE TITLE
Jakarta - June 2016 Report

### ISSUE THREAD

**Issue by brianking** [mozilla/community-spaces#22]
Compile and publish the space report for Jakarta, for June 2016.

**Comment by yofiesetiawan** [comment]
Hi, done with June 2016 Report https://docs.google.com/document/d/1eQCL5FW8jtz06LjNhqx0_ISDYknomiCwfHGkY6g73Ng/edit?usp=sharing

We run more sentiment updates on June 2016, and receive quite satisfying result.
97% This meetup was worth my time.
98% I would recommend future meetings of this meetup to my friends/colleagues
88% Accessibility of the Community Space using private or public transport
97% Courtesy & Friendliness of Mozillians at the Community Space
94% WiFi Internet Connectivity Speed
94% Cleanliness of the Community Space

https://docs.google.com/spreadsheets/d/1TLSY19pCZG_EdTWfu-aZATfLuGjneov3h2xxCK5ZG70/edit?usp=sharing
