### ISSUE TITLE
Setup repository for sharing materials

### ISSUE THREAD

**Issue by brianking** [mozilla/community-spaces#25]
One thing we discussed in London is where to share resources that are common among all spaces, or where any space can store their materials.

One solution is to use this github repository. We could start with a folder for each space, and sub-folders for docs, presenations, and so on. And then we would have a 'global' folder with useful assets for all spaces.

Open to alternative proposals.

@bobreyes @yofiesetiawan @bobchao @rara79 @alamanda @irvin

**Comment by irvin** [comment]
we should use shared google drive because github is not working quite well on documents and graphic files (also I think we would also have many google documents), and BobChao already opened a folder here, 
https://drive.google.com/folderview?id=0Bw6oD4FgXozEZ2NVSUtIMEFXT2M&usp=sharing

**Comment by irvin** [comment]
example for why git is not working well for graphic files - 
git will keep all stage of one files in repo, this, if I open a 100MB poster, add only one english character and save, the repo will growing another 100MB in size (each time when I save, it grows 100MB).

**Comment by bobreyes** [comment]
I will go for Dropbox or Google Drive instead of Github. Thanks!

**Comment by yofiesetiawan** [comment]
I agree to go with Dropbox or Google Drive...

**Comment by brianking** [comment]
For reference:

https://help.github.com/articles/working-with-large-files/

**Comment by bobchao** [comment]
Try to summary things, welcome to add more:

# Use GitHub
- Pro: Easier to find the entry point for general public (compare to Google Drive.)
- Pro: Easier to receive patches / files from the outside of the core-team (via PR)
- Pro: No complex privilege setting -- which is actually great for project like us, everything is fully open. 

# Use Google Drive
- Pro: Nonprogramer-friendly
- Pro: Easier to add files -- just copy the files you want to share into the folder, no commit log needed.
- Pro: Build-in, feature-complete editors & reader online.

**Comment by brianking** [comment]
\+ @kudodo who is working on a proposal that will include something related to this.

**Comment by kudodo** [comment]
Thank you @brianking .

Here is the first version of my draft. I am interested in demonstrating this idea in Mozilla Festival in October. Do you like this idea?
https://docs.google.com/document/d/1VJUFgAizJyGnMzBymFBysNENhaJGGGKX26XzOZLfe_w/edit?usp=sharing

**Comment by brianking** [comment]
Assigned to @irvin for deciding next steps.
