### ISSUE TITLE
2016 Wrap-up Blog Post

### ISSUE THREAD

**Issue by brianking** [mozilla/community-spaces#26]
While we finalise the charts in issue #18, we can start filling out the blog post. I've made a start here:

https://docs.google.com/document/d/1-cMJqR9MjTb-gESs9FFY5ktgL_4LHySygydYS4rECXM/edit?usp=sharing

@yofiesetiawan @irvin @bobreyes Please help me fill it out. In particular, please add your thoughts in the 'Happenings and Highlights' section. The type of information that would be good is:

* How you contributed to certain campaigns (marketing, policy, dev engagement, Activate, ...)
* Examples of events that stood out, and the reasons why
* Strengths of your space
* Challenges you have been having
* What you would like to see in 2017

**Comment by yofiesetiawan** [comment]
Hi Brian,

I've added for Jakarta, please review...

**Comment by brianking** [comment]
Hi Yofie,

Thanks for that. The content is general is good but I suggest the following changes:

* Don't put the the questions in. Instead just have paragraphs that have a story arc.
* For example events, I would also advise talking about some popular workshops and other themed events, in particular with developer impact
* Talk a little about other organisations/companies/communities you have worked with
* Add 1-2 photos!

Thanks.

**Comment by irvin** [comment]
Taipei WIP, will add more later today

**Comment by bobreyes** [comment]
MNL done. Sorry for the delay. Thanks!

**Comment by brianking** [comment]
Draft almost complete: https://docs.google.com/document/d/1-cMJqR9MjTb-gESs9FFY5ktgL_4LHySygydYS4rECXM/edit?usp=sharing

**Comment by brianking** [comment]
Published:

http://brian.kingsonline.net/talk/2017/01/community-spaces-in-2016/

https://blog.mozilla.org/community/2017/01/25/community-spaces-in-2016/
