### ISSUE TITLE
Community space report

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/community-spaces#27]
## Objective Goal:

Nice graphs and charts for April-December 2016 data gathered by the space stewards.

## Related documents and links
- Data dashboard https://docs.google.com/spreadsheets/d/1h8nsKT00FVrRLUu1-2hpM-p0GD3eHztYB5AqdKm0suw/edit#gid=2022809174

## Item list:
- [x] Pie chart showing total number of events all spaces (R:)
- [x] Pie chart showing total number of events per space (R:)
- [x] Pie chart showing total number of attendees in all spaces (R:)
- [x] Pie chart showing total number of attendees per space (R:) 
- [x] Total number of new attendees (R:)
- [x] Total number of returning attendees (R:)
- [x] Recap page (R:)

## Related Issues

[Reference meta issues and past issues] #

**Comment by brianking** [comment]
Done.

https://datastudio.google.com/open/0B1QBPp2E8AIKQVdpZTBFc1R2SjA

Thanks @kelimuttu !
