### ISSUE TITLE
Standardise Registration and Survey Forms

### ISSUE THREAD

**Issue by brianking** [mozilla/community-spaces#3]
For reference here are 2 working docs:

@bobreyes : https://docs.google.com/document/d/1bXXuPCdvajju9bt6rBH6lXTUZl9GzfzjcA-NKd3xRRQ/edit
@yofiesetiawan : https://docs.google.com/document/d/1nVYFoT7maDu33EZK9D-sBh4L4YGDTV6EU21SHR2TRFo/edit

We are solving for 2 things here, it seems.
1. Registration on arrival at the venue
2. Gathering sentiment and stats after the visit

I think Manila has #1 solved because of building requirements. Let's try and standardise here.

A few more thoughts:
1. How can we provide incentives for people to fill it out?
2. The registration on entry is the source of truth for numbers, as not everyone will fill out the survey after. So we need to capture there is they are new or return visitors.
3. I like the idea of having a single form (e.g. http://survey.mozspaces.org/) for all spaces. Do we know anyone who could work on this? We might need to ensure that random people coming to the form don't fill it out (spam) -- maybe a unique id (assigned to each event) passed to it unlocks it or something like that.
4. We need to ensure, for the next 3-6 months at least, that we are surfacing up numbers and sentiment around developer focused events.

**Comment by yofiesetiawan** [comment]
Hi,
I already made my format

Registration
http://goo.gl/forms/BcgcXHkdDM

Survey
http://goo.gl/forms/SG9UmxlUp0

**Comment by bobreyes** [comment]
@yofiesetiawan possible for us to see the contents of the online forms?

**Comment by yofiesetiawan** [comment]
@bobreyes we haven't use it yet..

**Comment by yofiesetiawan** [comment]
http://mozilla.or.id/spaceform this is the one that we are going to use for Jakarta Space...

**Comment by bobreyes** [comment]
@brianking William mentioned before something about the online registration system they use at the Mozilla Paris office. Perhaps we can build something around it.

**Comment by brianking** [comment]
I reached out to Shannon about the staff spaces system, and here is her reply:

---

Currently we are using Mozilla's own 'Peekaboo' system. However we are decommissioning this at some point in the near future and replacing it with another system. I don't have the exact details but you can reach out to Mark Jeffries who does have the information you're looking for. 

---

Therefore I recommend that we move forward with our own solution for now.

**Comment by yofiesetiawan** [comment]
Hi Brian,

Okay thanks, we (jakarta) can use google form for now.. Just let us know if
there are some specific data that Mozilla love to add to the registration
or survey form...

Regards,
Yofie Setiawan

**Comment by bobchao** [comment]
Hi, I made another one to explore the possibility: https://docs.google.com/document/d/18sTs7jhGfDsiB9kcGpCAvjZqgCYv7PYBvY_DGjgw5_o/edit#

Will keep follow this issue and modify the questionnaire

**Comment by yofiesetiawan** [comment]
Questions that i like:
Please tell us your Mozilla Community Space experience
What’s your favorite part of the Space?
What's you must disliked part of the Space?

**Comment by brianking** [comment]
@bobchao thanks, the doc you put together looks great. I added in a few comments. I think we are going in the right direction.

Once we finalise, we can find the survey host and ensure that we are able to separate out each space in the results.

**Comment by brianking** [comment]
Let's try and move towards a solution here. What is the best way forward? It is to take Bob Chao's doc and use that as the base, and then look for hosting?

Also, can you please share here the current forms you are using for both registration and event follow-ups, for reference. And if there is a public version of the results available that doesn't share personal info, please share as well.

**Comment by bobreyes** [comment]
For MNL, we are using http://survey.mozspacemnl.org while visitor registration is done manually via logsheet when visitors enter the Community Space.

I left my comments in Bob Chao's https://docs.google.com/document/d/18sTs7jhGfDsiB9kcGpCAvjZqgCYv7PYBvY_DGjgw5_o/edit#

I suggest that we finalize Bob Chao's survey document. As for the hosting platform, if we can have a surveymonkey or surveygizmo site instead of a Google Form. Thanks!

**Comment by bobchao** [comment]
@brianking When we host the survey together, is that mean we will not be able to collect answers "not in the standardized survey" we want to know from visitors ? I think there's always a need to add more questions for a specific event / special purpose.

**Comment by yofiesetiawan** [comment]
My personal suggestion, we can use any kind of form that suite to our local needs. But we need to have standard way to file a report to Mozilla. So we can still collect some sentiment surveys that might improve local needs.

Jakarta current survey form http://goo.gl/forms/SG9UmxlUp0

Informations we collect from Survey Form
- This meetup was worth my time.
- I would recommend future meetings of this meetup to my friends/colleagues.
- What i liked best about this meetup.
- Something that could be improved is.
- Other comments.
- Accessibility of the Community Space using private or public transport.
- Courtesy & Friendliness of Mozillians at the Community Space.
- WiFi Internet Connectivity Speed.
- Facilities / Amenities at the Community Space (rest rooms, tables, chairs, coffee, WiFi, elevator, etc).
- Cleanliness of the Community Space.

**Comment by bobchao** [comment]
Follow the thoughts from @yofiesetiawan, so
- The standardized form include questions that we must have in our local surveys
- Local team can add more questions for their needs in the localized version.
- After we collect the results, we can submit the answers required back to a central database for future analyze 

That sounds great to me.

**Comment by brianking** [comment]
For me the ideal solution would be that submitted responses, regardless of which space they come from, end up in the same place. This would reduce overhead of submitting responses by the space owners.

One thing worth noting though is language. We'll see responses in multiple languages, so even if we have everything in one place, we'll need someone to parse the replies and analyse. Because of this a common solution might not be the way to go, but I definitely want to solve for the issue of us collecting the same type of data.
