### ISSUE TITLE
Taipei - April 2016 Report

### ISSUE THREAD

**Issue by brianking** [mozilla/community-spaces#4]
Compile and publish the space report for Taipei, for April 2016.

**Comment by bobchao** [comment]
Done! :dancer: 

https://docs.google.com/document/d/1TXOVO4V-q6k_ZKfMd7GWyLS_TyzUXUjcXURnN3v8faI/edit

**Comment by brianking** [comment]
Thank you @bobchao 

I added a couple of questions/comments in the doc, let's follow up there.
