### ISSUE TITLE
Jakarta - April 2016 Report

### ISSUE THREAD

**Issue by brianking** [mozilla/community-spaces#5]
Compile and publish the space report for Jakarta, for April 2016.

**Comment by yofiesetiawan** [comment]
Hi Brian,
Are we still use the Google Drive? Or we should just post the content right here?

**Comment by yofiesetiawan** [comment]
Done!

https://docs.google.com/document/d/1EI_lafPytcWdQAbKeAmfYRDstUdf-Gnf85eXZxiGVYs/edit?usp=sharing

**Comment by brianking** [comment]
Thank Yofie. We can put the reports in the drive folder, plus post the link here. Make sure the doc permission is view only for public. You can add a link at the top to this issue for people to come and discuss.
