### ISSUE TITLE
Explore Innovation Lab idea for India Spaces with Innovation Team

### ISSUE THREAD

**Issue by brianking** [mozilla/community-spaces#7]
In Berlin a few weeks ago we (Participation and Innovation teams) talked about the possibility of working with our communities in India to start 1-2 innovation spaces. I'm starting this conversation to see if we want to pursue this.

There are plenty of models for hubs (business incubator, co-working, maker space, ...) but what we need to figure out is what model we want to use that is best for our needs, provides the best value to volunteers, and contains Mozilla values from the ground up.

Some very broad framing questions:
1. Is India the right place to start?
2. What criteria should we have for applications?
3. What would the first 6-12 months look like in the space?

**Comment by bobchao** [comment]
Any document about the intention to build a "innovation space" ?

**Comment by brianking** [comment]
Still early days. See:

https://github.com/mozilla/participation-org/issues/436

**Comment by brianking** [comment]
WONTFIX as we are pushing this off to later in the year. We'll open new issues at that time.
