### ISSUE TITLE
Update Affiliate Spaces SOP

### ISSUE THREAD

**Issue by brianking** [mozilla/community-spaces#8]
This document is out of date and was designed for the first wave of pilot spaces to get budget:

https://wiki.mozilla.org/ReMo/SOPs/Affiliate_Space

I also propose a terminology change.

Community Spaces = Official community spaces are ones where Mozilla provides funding for month-to-month costs such as rent and utilities, and provides guidance on activities in the space.

Affiliate Spaces = Affiliate community spaces are ones where Mozillians use other financial means to support a physical space that they work out of.

New documentation based on this is being tracked in issue #1

**Comment by MichaelKohler** [comment]
I think it would make sense to have this redirect to the other wiki page from #1 and describe the process there. What do you think? IMHO this is not Reps SOP material anymore.

**Comment by brianking** [comment]
@MichaelKohler agreed in general, and one less SOP is 'a good thing'. Will be exploring with @rosanardila on how to work with affiliate spaces for CD innovation efforts, but we can document that separately as needed.

**Comment by brianking** [comment]
I've added an out of date banner to the page for now, pointing people to the new page.

![firefox_screenshot_2016-07-06t12-53-43 757z](https://cloud.githubusercontent.com/assets/114116/16618422/8a71ac52-4389-11e6-931d-d9b3279a960f.png)

My understanding is that all Remo wiki pages will be archived soon anyway as we move to a new platform for Reps documentation.

**Comment by brianking** [comment]
This page has now been removed from the wiki.
