### ISSUE TITLE
Jakarta Opening Blog Post

### ISSUE THREAD

**Issue by brianking** [mozilla/community-spaces#9]
Blog post on https://blog.mozilla.org/community about the successful opening event, and what the Space means in the local and global context.

Can use some of @yofiesetiawan 's photos, with permission.
https://flic.kr/s/aHskwtBAYH
- @rara79 @alamanda

**Comment by brianking** [comment]
@fauzanalfi to make first draft.

**Comment by fauzanalfi** [comment]
@brianking current blogpost draft can be viewed here: https://docs.google.com/document/d/1YaR5wA3oD6bPqtRY_lvwij-LxXcbFfg0lREWccRWOsQ/edit?usp=sharing

Blog post skeleton structure:
- Blog post intro and Space overview
- Opening event recap
- Space details (what's inside – incl. facilities & activities – what will the community do with the space)
- Planning, preparation and design process (in general, highlighting participatory design and planning process within the community)
- Space meaning in local and global context

Please add anything necessary to the structure if needed, @yofiesetiawan @rara79 @alamanda

**Comment by brianking** [comment]
@fauzanalfi the post is great, I don't really have anything to add. I just made some minor grammar updates.

The next step is to add pictures, do you want to do that?

**Comment by fauzanalfi** [comment]
@brianking I've added some pictures. Please check.

**Comment by brianking** [comment]
Looks good except for the first one, where Thunderbird is very prominent!

**Comment by fauzanalfi** [comment]
@brianking oh ok. I change the first picture. Please check again. Thanks.

**Comment by brianking** [comment]
And ... we're done.

https://blog.mozilla.org/community/2016/05/19/jakarta-community-space-launch/
